apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Atest1"
  description: "testing"
  links:
    - title: TIBCO Cloud Home
      url: https://cloud.tibco.com/
    - title: Documentation
      url: https://eu.integration.cloud.tibco.com/docs/index.html
    - title: TIBCO Cloud Integration
      url: https://eu.integration.cloud.tibco.com/applications
  annotations:
    github.com/project-slug: TIBCO-Hub-Backstage/Atest1
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: development
  owner: "group:default/acme"
  providesApis: [ "Atest1-api" ]
